quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl

quarkus.kubernetes.deployment-target=knative
quarkus.container-image.group=omatheusmesmo

quarkus.smallrye-openapi.info-title=Quarkus Cloud Native Demo
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Event Processor API demonstrating Quarkus native compilation for serverless and Knative

quarkus.native.resources.includes=webhook-schema.json

%dev.quarkus.hibernate-orm.sql-load-script=no-file
%test.quarkus.hibernate-orm.sql-load-script=no-file

%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/cloudnative
%prod.quarkus.datasource.username=quarkus
%prod.quarkus.datasource.password=quarkus
